# -------------------------------------------------------------------------------------
#
# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained 
# herein is strictly forbidden, unless permitted by WSO2 in accordance with the 
# WSO2 Commercial License available at https://wso2.com/licenses/eula/3.2
#
# --------------------------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "apim-helm-km.fullname" . }}-ingress
  namespace : {{ .Release.Namespace }}
{{- if .Values.kubernetes.ingress.km.annotations }}
  annotations:
{{ toYaml .Values.kubernetes.ingress.km.annotations | indent 4 }}
    {{- if .Values.kubernetes.ingress.ratelimit.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: | 
      limit_req zone={{ .Values.kubernetes.ingress.ratelimit.zoneName }} burst={{ .Values.kubernetes.ingress.ratelimit.burstLimit }} nodelay;                                                   
      limit_req_status 429;
      set $rangeheadervalue $http_range;
      if ($http_accept_encoding = "gzip") {
      set $rangeheadervalue "";
      }
      proxy_set_header Range $rangeheadervalue;
    {{- end }}
{{- end }}
spec:
  ingressClassName: {{ .Values.kubernetes.ingressClass }}
  tls:
  - hosts:
    - {{ .Values.kubernetes.ingress.km.hostname }}
    secretName: {{ .Values.kubernetes.ingress.tlsSecret }}
  rules:
  - host: {{ .Values.kubernetes.ingress.km.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ template "apim-helm-km.fullname" . }}-service
            port: 
              number: {{ add 9443 .Values.wso2.apim.portOffset }}
