env:
  contexts:
    - name: graphql-context
      urls:
        - http://tawa.local:3000/graphql
      includePaths:
        - http://tawa.local:3000/.*

parameters:
  failOnError: false
  progressToStdout: true
 
customScanPolicies:
  - name: fast-graphql-scan-policy
    rules:
      - id: 40012  # SQL Injection
        name: SQL Injection
        description: Detects classic SQL injection vulnerabilities.
        threshold: HIGH
        strength: LOW
      - id: 40018  # SQL Injection PostgreSQL
        name: SQL Injection - PostgreSQL
        description: Detects PostgreSQL-specific SQL injection patterns.
        threshold: HIGH
        strength: LOW
      - id: 40020  # XSS
        name: Cross Site Scripting (XSS)
        description: Detects reflected XSS vulnerabilities.
        threshold: HIGH
        strength: LOW
      - id: 40016  # DOM XSS
        name: DOM XSS
        description: Detects DOM-based Cross Site Scripting.
        threshold: HIGH
        strength: LOW
      - id: 40035  # GraphQL Introspection Enabled
        name: GraphQL Introspection Enabled
        description: Identifies GraphQL endpoints with introspection enabled.
        threshold: HIGH
        strength: LOW
      - id: 10095  # Cookie Without HttpOnly Flag
        name: Cookie Without HttpOnly
        description: Checks for cookies missing the HttpOnly flag.
        threshold: HIGH
        strength: LOW
      - id: 10094  # Cookie Without Secure Flag
        name: Cookie Without Secure
        description: Checks for cookies missing the Secure flag.
        threshold: HIGH
        strength: LOW

jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10

  - type: spider
    parameters:
      context: graphql-context
      maxDuration: 1

  - type: graphql
    parameters:
      context: graphql-context
      endpoint: http://tawa.local:3000/graphql

  - type: activeScan
    parameters:
      context: graphql-context
      policy: fast-graphql-scan-policy

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap-report-graphql-light.html
