{
 "title": "Network Gateway",
 "description": "Main dashboard for the network gateway",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Data Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Connection",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{ name=\"database_connection_check\", container=\"data-aggregator\"}) / count(aspnetcore_healthcheck_status{ name=\"database_connection_check\", container=\"data-aggregator\"})"
    }
   ]
  },
  {
   "title": "Health Check",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{ name=\"aggregator_health_check\", container=\"data-aggregator\"}) / count(aspnetcore_healthcheck_status{ name=\"aggregator_health_check\", container=\"data-aggregator\"})"
    }
   ]
  },
  {
   "title": "Time delay between Aggregator and Round Timestamp",
   "type": "timeseries",
   "description": "All three numbers are slightly different numbers to measure.\n\nLag at last commit measures the \"best case\", Lag at last loop start measures the \"current situation\" and \"Peak lag before last commit\" measures the worst case.\n \nA large number here indicates either a delay between network commit and the aggregator ingestion somewhere OR clock drift between the Data Aggregator and Network.",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(avg_over_time(ng_ledger_commit_peak_round_timestamp_data_aggregator_clock_delay_before_last_commit_seconds{container=\"data-aggregator\"}[$__interval]))",
     "legendFormat": "Avg peak lag before last commit"
    }
   ]
  },
  {
   "title": "Ingestion Rate",
   "type": "timeseries",
   "description": "Includes system transactions",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_ledger_commit_committed_transactions_count{ container=\"data-aggregator\"}[$__interval])) ",
     "legendFormat": "data-aggregator"
    }
   ]
  },
  {
   "title": "Ledger Batch Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "sum(rate(ng_ledger_commit_batch_commit_time_seconds_count{container=\"data-aggregator\", }[$__interval]))\n"
    }
   ]
  },
  {
   "title": "Time since last DB Update",
   "type": "stat",
   "description": "This number includes the time for the metrics to get to Grafana and render the dashboard! A time <10 seconds is expected.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - (max(ng_ledger_commit_last_commit_timestamp_seconds{} > 0) OR (max(max_over_time(ng_ledger_commit_last_commit_timestamp_seconds{}[$__range]) > 0))))"
    }
   ]
  },
  {
   "title": "Synced Up Nodes",
   "type": "stat",
   "description": "The number of nodes which are sufficiently synced up to contribute to calculations on ledger extension.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ng_ledger_sync_sufficiently_synced_up_nodes_total{container=\"data-aggregator\", })"
    }
   ]
  },
  {
   "title": "Nodes to commit",
   "type": "stat",
   "description": "The number of nodes which are sufficiently synced up to contribute to calculations on ledger extension.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ceil(ng_ledger_sync_sufficiently_synced_up_nodes_total{container=\"data-aggregator\", }\n* ng_ledger_sync_trust_weighting_required_for_quorum_total{container=\"data-aggregator\", }\n/ ng_ledger_sync_sufficiently_synced_up_nodes_trust_weighting_total{container=\"data-aggregator\", }\n))"
    }
   ]
  },
  {
   "title": "DB State Version",
   "type": "stat",
   "description": "The number of nodes which are sufficiently synced up to contribute to calculations on ledger extension.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(ng_ledger_commit_tip_state_version{container=\"data-aggregator\", }[$__interval]))",
     "legendFormat": "State Version"
    }
   ]
  },
  {
   "title": "Target Lag",
   "type": "stat",
   "description": "The highest seen target state version across nodes, minus the database state version.\n\nThis can be negative because the Core API can report a target state version less than its ledger tip somehow.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(ng_node_ledger_target_state_version{container=\"data-aggregator\", }[$__interval]))\n- max(max_over_time(ng_ledger_commit_tip_state_version{container=\"data-aggregator\", }[$__interval]))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Node state version vs Gateway DB",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "max by (node) (max_over_time(ng_node_ledger_tip_state_version{container=\"data-aggregator\"}[$__interval]))\n- ignoring (node) group_left max(max_over_time(ng_ledger_commit_tip_state_version{container=\"data-aggregator\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Worker error count",
   "type": "timeseries",
   "description": "Broken down by worker, node and error.\n(Summed over each interval)",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(ng_workers_global_error_count{ container=\"data-aggregator\"}[$__interval])) by (worker, error) > 0",
     "legendFormat": " ()"
    },
    {
     "expr": "sum(increase(ng_workers_node_error_count{ container=\"data-aggregator\"}[$__interval])) by (worker, node, error) > 0",
     "legendFormat": ":  ()"
    }
   ]
  },
  {
   "title": "P90 transaction batch fetch time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, avg(rate(ng_node_fetch_transaction_batch_time_seconds_bucket{ container=\"data-aggregator\"}[5m])) by (le, node))"
    }
   ]
  },
  { "title": "Gateway API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RO Database Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{ name=\"readonly_database_connection_check\", container=\"gateway-api\"}) / count(aspnetcore_healthcheck_status{ name=\"readonly_database_connection_check\", container=\"gateway-api\"})"
    }
   ]
  },
  {
   "title": "RW Database Connection",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aspnetcore_healthcheck_status{ name=\"readwrite_database_connection_check\", container=\"gateway-api\"}) / count(aspnetcore_healthcheck_status{ name=\"readwrite_database_connection_check\", container=\"gateway-api\"})"
    }
   ]
  },
  {
   "title": "Requests by action",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{ container=\"gateway-api\"}[5m])) by (action)"
    }
   ]
  },
  {
   "title": "P95 response latency by action (in preceding 5 mins)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", container=\"gateway-api\"}[5m])) by (le, action))"
    }
   ]
  },
  {
   "title": "Response HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{ container=\"gateway-api\"}[5m])) by (code)"
    }
   ]
  },
  {
   "title": "API percentile request latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", container=\"gateway-api\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\", container=\"gateway-api\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{code=~\"[23]..\",  container=\"gateway-api\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Top 10 API Errors in Time Period",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(ng_gateway_response_error_count{ container=\"gateway-api\"}[$__range])) by (action, status_code, exception, gateway_error) > 0)",
     "legendFormat": "  (, )"
    }
   ]
  },
  {
   "title": "Delay between Gateway API clock and Round Timestamp",
   "type": "timeseries",
   "description": "A large number here indicates either a delay between network commit and the aggregator ingestion (see graph above), a DB replication delay OR clock drift between the Gateway API/s and Network.",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(min_over_time(ng_gateway_ledger_tip_round_timestamp_gateway_api_clock_lag_at_last_request_seconds{ container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Min delay (across all requests and Gateway APIs)"
    },
    {
     "expr": "max(max_over_time(ng_gateway_ledger_tip_round_timestamp_gateway_api_clock_lag_at_last_request_seconds{ container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Max delay (across all requests and Gateway APIs)"
    }
   ]
  },
  {
   "title": "API Error Response Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_gateway_response_error_count{ container=\"gateway-api\"}[$__interval])) by (action, status_code, exception, gateway_error) > 0",
     "legendFormat": "  (, )"
    }
   ]
  },
  {
   "title": "Healthy Core APIs by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "targets": [
    {
     "expr": "ng_nodes_gateway_health_check_node_statuses{container=\"gateway-api\",status=\"HEALTHY_AND_SYNCED\"}"
    }
   ]
  },
  {
   "title": "Lagging Core APIs by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "ng_nodes_gateway_health_check_node_statuses{container=\"gateway-api\",status=\"HEALTHY_BUT_LAGGING\"}"
    }
   ]
  },
  {
   "title": "Unhealthy Core APIs by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
   "targets": [
    {
     "expr": "ng_nodes_gateway_health_check_node_statuses{container=\"gateway-api\",status=\"UNHEALTHY\"}"
    }
   ]
  },
  {
   "title": "Mempool and Transaction Submission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "Resubmission queue",
   "type": "stat",
   "description": "Count of transactions needing resubmission",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ng_db_mempool_transactions_needing_resubmission_total{ container=\"data-aggregator\"}) by (container)"
    }
   ]
  },
  {
   "title": "Mempool transaction status changes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 3, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "sum(rate(ng_db_mempool_transactions_added_from_gateway_submission_count{ container=\"gateway-api\"}[5m]))",
     "legendFormat": "First submitted to Gateway"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_added_from_node_mempool_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Discovered in node mempool"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_as_missing_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Now missing"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_assumed_in_node_mempool_after_resubmission_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Resubmitted"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_reappeared_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Reappeared"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_as_failed_for_timeout_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Timeout failure"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_failed_from_initial_submission_count{ container=\"gateway-api\"}[5m]))",
     "legendFormat": "Failed at submission"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_failed_during_resubmission_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Failed at resubmission"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_resolved_but_unknown_status_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Yet unknown resolution"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_committed_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(ng_db_mempool_transactions_marked_committed_which_were_failed_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Committed after failed"
    }
   ]
  },
  {
   "title": "Mempool size by node",
   "type": "timeseries",
   "description": "The mempool union can lag slightly behind individual nodes, as we combine the latest snapshot of the node mempools regularly.\n\nIt also only includes transactions we've managed to read the contents of we can \"miss\" transactions which leave the mempool before we managed to read their contents.",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "avg(ng_node_mempool_combined_current_size_total{container=\"data-aggregator\"})",
     "legendFormat": "Mempool union across all nodes"
    },
    {
     "expr": "avg(ng_node_mempool_size_total{ container=\"data-aggregator\"}) by (node)",
     "legendFormat": "Node: "
    }
   ]
  },
  {
   "title": "DB Mempool Transactions table size by status",
   "type": "timeseries",
   "description": "The DB table gets pruned regularly. Committed currently get pruned after a few seconds, Failed/Missing after a week. \n\nExcessive MISSING typically indicates a race condition between non-Gateway Txns being discovered in a mempool and being committed to the DB ledger.",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 71 },
   "targets": [
    {
     "expr": "avg(ng_db_mempool_size_by_status_total{ container=\"data-aggregator\"}) by (status)"
    }
   ]
  },
  {
   "title": "Txn Status Flips [24h]",
   "type": "stat",
   "description": "Count of any pending transactions temporarily marked as failed before being marked as committed in the last 24h. We don't want this to ever happen.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ng_db_mempool_transactions_marked_committed_which_were_failed_count{ container=\"data-aggregator\"}[24h])) or vector(0)"
    }
   ]
  },
  {
   "title": "Initial transaction submission node requests",
   "type": "timeseries",
   "description": "The Attempt/Error/Success lines show the request response. The Result: X lines show what happened at initial submission to a node.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_construction_transaction_submission_request_count{ container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Attempt"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_submission_error_count{ container=\"gateway-api\"}[$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_submission_success_count{ container=\"gateway-api\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_submission_resolution_count{ container=\"gateway-api\"}[5m])) by (result)",
     "legendFormat": "Result: "
    }
   ]
  },
  {
   "title": "Transaction resubmission node requests",
   "type": "timeseries",
   "description": "The Attempt/Error/Success lines show the overall status of the resubmission request made to the node. The Result: X lines show a more detailed view by error code.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_attempt_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Attempt"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_error_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_success_count{ container=\"data-aggregator\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(ng_construction_transaction_resubmission_resolution_count{ container=\"data-aggregator\"}[5m])) by (result)",
     "legendFormat": "Result: "
    }
   ]
  }
 ]
}