{
 "title": "Radix Node Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nodeinfo" }
   ]
  },
  {
   "title": "Versions / Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(info_counters_sync_target_state_version[1m])"
    }
   ]
  },
  {
   "title": "% Synced",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - ((info_counters_sync_target_state_version-info_counters_sync_current_state_version) / info_counters_sync_target_state_version)) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "info_counters_time_duration" }
   ]
  },
  {
   "title": "Current Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_counters_sync_current_state_version"
    }
   ]
  },
  {
   "title": "Target Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "info_counters_sync_target_state_version"
    }
   ]
  },
  {
   "title": "Instance Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mynode\"}"
    }
   ]
  },
  {
   "title": "Release",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodeinfo" }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "View In Epoch",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 18, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "info_epochmanager_currentview_view",
       "legendFormat": "View"
      }
     ]
    },
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "info_epochmanager_currentview_epoch"
      }
     ]
    },
    {
     "title": "Address",
     "type": "stat",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nodeinfo" }
     ]
    },
    {
     "title": "Registered Validator",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nodeinfo{validator_registered=\"true\"}"
      }
     ]
    },
    {
     "title": "Validator Address",
     "type": "stat",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "nodeinfo" }
     ]
    },
    {
     "title": "Node Key",
     "type": "stat",
     "gridPos": { "h": 2, "w": 18, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nodeinfo" }
     ]
    },
    {
     "title": "Validator Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nodeinfo{is_in_validator_set=\"true\"}"
      }
     ]
    },
    {
     "title": "Mempool Size",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "info_counters_mempool_current_size"
      }
     ]
    },
    {
     "title": "Mempool Additions / Second",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(info_counters_mempool_add_success{}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Radix Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Peers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "total_peers" }
     ]
    },
    {
     "title": "Network Peers Over Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "total_peers", "legendFormat": "Peers" }
     ]
    },
    {
     "title": "Network Validators",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "total_validators" }
     ]
    },
    {
     "title": "Network Validators Over Time",
     "type": "graph",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "total_validators", "legendFormat": "Validators" }
     ]
    },
    {
     "title": "Current Fork Name",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nodeinfo" }
     ]
    },
    {
     "title": "Fork Voting Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 17, "x": 7, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nodeinfo" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "processcpuload", "legendFormat": "Process CPU Load" },
      { "expr": "systemcpuload", "legendFormat": "System CPU Load" }
     ]
    },
    {
     "title": "Heap Memory Usage Over Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "heapmemoryusage_max", "legendFormat": "Maximum Heap Size" },
      { "expr": "heapmemoryusage_used", "legendFormat": "Used Heap Size" }
     ]
    },
    {
     "title": "Heap Memory Usage %",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(heapmemoryusage_used / heapmemoryusage_max) * 100",
       "legendFormat": "used"
      },
      { "legendFormat": "max" }
     ]
    }
   ]
  }
 ]
}