#!/bin/bash

echo   "##########################################################"
echo   "##   Installing Code-Server on WSL2 (Ubuntu 20.04)    ##"
echo   "##########################################################"

printf ">> Downloading and unzipping Code-Server.\n"
mkdir -p ~/.local/lib ~/.local/bin
curl -fL https://github.com/cdr/code-server/releases/download/v3.4.1/code-server-3.4.1-linux-amd64.tar.gz \
  | tar -C ~/.local/lib -xz
mv ~/.local/lib/code-server-3.4.1-linux-amd64 ~/.local/lib/code-server-3.4.1
ln -s ~/.local/lib/code-server-3.4.1/bin/code-server ~/.local/bin/code-server

printf ">> Installing Extension: Shan.code-settings-sync. \n"
code-server --install-extension Shan.code-settings-sync
printf "\nGet a trusted Gist ID to restore extensions and configurations through Settings-Sync extension:\n"
printf "\t https://gist.github.com/chilcano/b5f88127bd2d89289dc2cd36032ce856 \n"

printf ">> Installing 'mkcert' (https://github.com/FiloSottile/mkcert) .\n"
MKCERT_BUNDLE_URL=$(curl -s https://api.github.com/repos/FiloSottile/mkcert/releases/latest | jq -r -M '.assets[].browser_download_url | select(contains("linux-amd"))')
MKCERT_BUNDLE_NAME="${MKCERT_BUNDLE_URL##*/}"

if [ -f "${MKCERT_BUNDLE_NAME}" ]; then
    printf ">> The $MKCERT_BUNDLE_NAME file exists. Nothing to download. \n"
else
    printf ">> The file doesn't exist. Downloading the $MKCERT_BUNDLE_NAME file. \n"
    wget -q $MKCERT_BUNDLE_URL
fi
cp $MKCERT_BUNDLE_NAME mkcert
chmod +x mkcert

printf ">> Generating TLS certs with 'mkcert' for 'Code-Server'.\n"
mkcert -install
mkcert localhost 127.0.0.1 ::1

printf ">> Trust on the Root CA crt generated by 'mkcert'.\n"
printf ">> E.g. You can install it in your browser as trusted CA.\n"
printf ">> You can found the Root CA here: /home/<WLS2_USER>/.local/share/mkcert/rootCA.pem \n"

printf ">> Installation of 'Code-Server', 'mkcert' completed and TLS certs generated.\n"
printf ">> Now you can start 'Code-Server' executing these commands:\n"
printf "\t code-server                                    # starts using default config (~/.config/code-server/config.yaml) \n"
printf "\t code-server --auth none  --disable-telemetry   # starts without authn, in port 8080 and without telemetry \n\n"
printf "\t code-server --disable-telemetry --bind-addr 127.0.0.1:8443 --cert localhost+2.pem --cert-key localhost+2-key.pem   # uses created TLS certs \n"

