apiVersion: v1
kind: Service
metadata:
  name: {{ template "safeline.detector" . }}
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  ports:
    - name: tcd
      port: {{ template "safeline.detector.tcd.port" . }}
    - name: sns
      port: {{ template "safeline.detector.sns.port" . }}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: detector
