apiVersion: v1
kind: Service
metadata:
  name: "{{ template "safeline.mario" . }}"
  labels:
{{ include "safeline.labels" . | indent 4 }}
spec:
  ports:
    - name: mario
      protocol: TCP
      port: {{ template "safeline.mario.port" . }}
  selector:
{{ include "safeline.matchLabels" . | indent 4 }}
    component: mario
