---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: zap-scan-cronjob
  namespace: dast
  labels:
    app: zap-scan-cronjob
spec:
  schedule: "30 8 * * 2,5"  # tue and fri at 8.30h
  timeZone: "Europe/Madrid"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: zap-scan-cronjob
        spec:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - zap-scan
                    topologyKey: kubernetes.io/hostname
          containers:
            - name: zap-job
              image: zaproxy/zap-stable:2.16.1
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "== Updating OWASP ZAP Addons =="
                  zap.sh -cmd -addonupdate
                  now=$(date +%y%m%d-%H%M%S)
                  # echo "== Running OWASP ZAP at ${now} =="
                  # echo "** Scan JuiceShop **"
                  # REPORT_DATE=$now REPORT_DIR=/zap/wrk/out PRODUCT_NAME=JUICESHOP zap.sh -cmd -autorun /zap/wrk/plans/scan-plan-test1.yaml
                  echo "** Scan CyberChef **"
                  REPORT_DATE=$now REPORT_DIR=/zap/wrk/out PRODUCT_NAME=CYBERCHEF zap.sh -cmd -autorun /zap/wrk/plans/scan-plan-test2.yaml
                  echo "** Scan Console-Front **"
                  REPORT_DATE=$now REPORT_DIR=/zap/wrk/out PRODUCT_NAME=FRONT zap.sh -cmd -autorun /zap/wrk/plans/scan-plan-01.yaml
                  echo "** Scan Console-Back **"
                  REPORT_DATE=$now REPORT_DIR=/zap/wrk/out PRODUCT_NAME=BACK zap.sh -cmd -autorun /zap/wrk/plans/scan-plan-02.yaml
              volumeMounts:
                - name: zap-reports-dir
                  mountPath: /zap/wrk/out/
                - name: zap-scan-plans-dir
                  mountPath: /zap/wrk/plans/
                - name: zap-scan-policies-dir
                  subPath: my-policy-01
                  mountPath: /home/zap/.ZAP/policies/my-policy-01.policy
                - name: zap-scan-policies-dir
                  subPath: my-policy-02
                  mountPath: /home/zap/.ZAP/policies/my-policy-02.policy
                - name: zap-reimport-script
                  subPath: run-zap-and-defectdojo-reimport-sh
                  mountPath: /zap/wrk/run-zap-and-defectdojo-reimport.sh
          restartPolicy: Never
          volumes:
            - name: zap-reports-dir
              persistentVolumeClaim:
                claimName: zap-reports-pvc
            - name: zap-scan-plans-dir
              configMap:
                name: zap-scan-plans
            - name: zap-scan-policies-dir
              configMap:
                name: zap-scan-policies
            - name: zap-reimport-script
              configMap:
                name: zap-reimport-script
---